### ISSUE TITLE
Download Limited

### ISSUE THREAD

**Issue by Malte0621** [PixGuy/Finobe#1]
Please upload this to a mega or something.. It cannot be downloaded otherwise.

**Comment by PixGuy** [comment]
cough cough, excuse me, sir, what is A MEGA?
did you mean to say Mega Limited?
that hosting service?
Anyways, ill make a new one with the newer version of the website
this one is way too old

**Comment by Malte0621** [comment]
okay..

**Comment by Malte0621** [comment]
If you can send the link... (I got discord, Malte0621#4433) Im closing this "issue" now.
